# Generated by Django 4.1.3 on 2022-11-10 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cel_wizyt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cel', models.CharField(max_length=100)),
                ('id_lekarza', models.IntegerField()),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('temat', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('data_wpisu', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(max_length=3)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
